name: Auto Label PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PR_ACTIONS }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyGithub
        run: pip install PyGithub

      - name: Run Label Checker Script
        env:
          GITHUB_TOKEN: ${{ secrets.PR_ACTIONS }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}
          BRANCH_NAME: ${{ github.head_ref }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: python scripts/label-checker.py
